name: py38
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.4=hca03da5_0
  - cffi=1.17.0=py38h858044d_0
  - cutadapt=4.9=py38h24147e2_2
  - dnaio=1.2.2=py38h24147e2_0
  - hisat2=2.2.1=haef7865_8
  - icu=75.1=hfee45f7_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.5.4=h5503f6c_0
  - pbzip2=1.1.13=h8e2fd4a_2
  - perl=5.40.2=0_h80987f9_perl5
  - pigz=2.8=h93a6450_1
  - pip=24.2=py38hca03da5_0
  - pycparser=2.22=pyhd8ed1ab_0
  - python=3.8.20=h7d35d02_2_cpython
  - python-zlib-ng=0.5.0=py38he0129f3_0
  - python_abi=3.8=8_cp38
  - readline=8.3=h0b18652_0
  - samtools=0.1.19=h267f7b9_14
  - setuptools=75.1.0=py38hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.44.0=py38hca03da5_0
  - xopen=2.0.2=py38h150bfb4_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.23.0=py38h43bb1b3_0
  - zstd=1.5.6=hb46c0d2_0
prefix: /Users/bachen/miniconda3/envs/py38
